### User Register
POST http://localhost:4000/common-api/login
Content-Type: application/json

{
  "firstName": "Anurag",
  "lastName": "Sharma",
  "email": "anurag.user@example.com",
  "password": "User@12345",
  "profileImageUrl": "https://example.com/avatars/user.png",
  "role":"USER"
}

### User Login
POST http://localhost:4000/user-api/authenticate
Content-Type: application/json

{
  "email": "anurag.user@example.com",
  "password": "User@12345",
  "role":"USER"
}


//===========================================================================================


### Author Register
POST http://localhost:4000/common-api/login
Content-Type: application/json

{
  "firstName": "Vikas",
  "lastName": "Author",
  "email": "vikas.author@example.com",
  "password": "Author@12345",
  "profileImageUrl": "https://example.com/avatars/author.png",
  "role":"AUTHOR"
}


### Author Register
POST http://localhost:4000/author-api/users
Content-Type: application/json

{
  "firstName": "test",
  "lastName": "Author",
  "email": "test.author@example.com",
  "password": "testauthor",
  "profileImageUrl": "https://example.com/avatars/author.png"
}

### Author Login
POST http://localhost:4000/author-api/authenticate
Content-Type: application/json

{
  "email": "vikas.author@example.com",
  "password": "Author@12345",
  "role":"AUTHOR"
}



### Create article (AUTHOR)
POST http://localhost:4000/author-api/articles
Content-Type: application/json

{
  "author":"698abc7cab18fa7d80e894f9",
  "title":"test2 article",
  "category":"programming",
  "content":"content of test2 article"
}



###Read articles of a author
GET http://localhost:4000/author-api/articles/698965b85a08a6721a29ef61



### Update article (AUTHOR)
PUT http://localhost:4000/author-api/articles
Content-Type: application/json

{
  "author":"6989799b7013502767d3f82b",
  "articleId":"698981d2b54ba14743e2e94a",
  "title":"test2 article updated",
  "category":"programming",
  "content":"content of test2 article updated"
}



### Logout
POST http://localhost:4000/common-api/logout

//===================================================================================================
//admin login
###
post http://localhost:4000/admin-api/authenticate
Content-Type: application/json

{
  "email": "admin@gamil.com",
  "password": "admin",
  "role":"ADMIN"
}

//blocking of the users
###
post http://localhost:4000/admin-api/block
Content-Type: application/json

{
  "userid":"698abc2bab18fa7d80e894f7",
  "isActive":false
}

//unblocking the user
###
post http://localhost:4000/admin-api/unblock
Content-Type: application/json

{
  "userid":"698abc2bab18fa7d80e894f7",
  "isActive":true
}

//readig all the articles of the given user
###
GET http://localhost:4000/admin-api/read-articles/698abc7cab18fa7d80e894f9
