


###CREATE PRODUCTS

POST http://localhost:5000/products-api/products
Content-Type: application/json

{
    "productname":"LG Refrigerator",
    "price":"50000",
    "brand":"LG"
}



###create user req
POST http://localhost:5000/user-api/users
Content-Type: application/json

{
    "name":"Subhash",
    "email":"subhash@gmail.com",
    "password":"subhash",
    "cart":[]
}

###
GET http://localhost:5000/user-api/users/6981905fcca4861e74e0fc9a

###add product to users cart
PUT http://localhost:5000/user-api/user-cart/user-id/6981905fcca4861e74e0fc9a/product-id/69817e1c883617ba24de0230